development:
  adapter: postgresql
  encoding: unicode
  database: road_trip_dev
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: road_trip_dev
  pool: 5
  password: